"""add recommendations table

Revision ID: efca0238f7d5
Revises: c2aac2351f06
Create Date: 2026-06-01 01:38:53.607581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efca0238f7d5'
down_revision: Union[str, None] = 'c2aac2351f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumes_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_profile_id'), table_name='resumes')
    op.drop_table('resumes')
    op.add_column('skills', sa.Column('display_name', sa.String(length=100), nullable=False))
    op.add_column('skills', sa.Column('category', sa.String(length=50), nullable=True))
    op.alter_column('skills', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Nom affiché de la compétence (ex: Python, Communication)',
               existing_nullable=False)
    op.alter_column('skills', 'skill_type',
               existing_type=postgresql.ENUM('hard', 'soft', name='skilltype'),
               type_=sa.String(length=10),
               comment=None,
               existing_comment='hard (technique) ou soft (comportementale)',
               existing_nullable=False)
    op.alter_column('skills', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_skills_normalized_name'), table_name='skills')
    op.create_index(op.f('ix_skills_category'), 'skills', ['category'], unique=False)
    op.drop_column('skills', 'sub_category')
    op.drop_column('skills', 'updated_at')
    op.drop_column('skills', 'is_active')
    op.drop_column('skills', 'normalized_name')
    op.drop_column('skills', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Description libre de la compétence'))
    op.add_column('skills', sa.Column('normalized_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False, comment='Nom normalisé lowercase sans ponctuation — clé de matching NLP'))
    op.add_column('skills', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False, comment="False = désactivée, non suggérée dans l'UI ni utilisée par le NLP"))
    op.add_column('skills', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('skills', sa.Column('sub_category', postgresql.ENUM('programming', 'ai_ml', 'nlp', 'web_frontend', 'web_backend', 'big_data', 'database', 'devops', 'data_viz', 'security', 'management', 'soft_skill', 'other', name='skillcategory'), autoincrement=False, nullable=True, comment='Sous-domaine optionnel : programming, ai_ml, database, devops…'))
    op.drop_index(op.f('ix_skills_category'), table_name='skills')
    op.create_index(op.f('ix_skills_normalized_name'), 'skills', ['normalized_name'], unique=True)
    op.alter_column('skills', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('skills', 'skill_type',
               existing_type=sa.String(length=10),
               type_=postgresql.ENUM('hard', 'soft', name='skilltype'),
               comment='hard (technique) ou soft (comportementale)',
               existing_nullable=False)
    op.alter_column('skills', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Nom affiché de la compétence (ex: Python, Communication)',
               existing_nullable=False)
    op.drop_column('skills', 'category')
    op.drop_column('skills', 'display_name')
    op.create_table('resumes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('raw_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_parsed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('resumes_profile_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('resumes_pkey'))
    )
    op.create_index(op.f('ix_resumes_profile_id'), 'resumes', ['profile_id'], unique=False)
    op.create_index(op.f('ix_resumes_id'), 'resumes', ['id'], unique=False)
    # ### end Alembic commands ###