"""add skills table

Revision ID: f2e9433b69cc
Revises: 75c1d9cec673
Create Date: 2026-05-09 07:41:51.499132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e9433b69cc'
down_revision: Union[str, None] = '75c1d9cec673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Nom affiché de la compétence (ex: Python, Communication)'),
    sa.Column('normalized_name', sa.String(length=100), nullable=False, comment='Nom normalisé lowercase sans ponctuation — clé de matching NLP'),
    sa.Column('skill_type', sa.Enum('hard', 'soft', name='skilltype'), nullable=False, comment='hard (technique) ou soft (comportementale)'),
    sa.Column('sub_category', sa.Enum('programming', 'ai_ml', 'nlp', 'web_frontend', 'web_backend', 'big_data', 'database', 'devops', 'data_viz', 'security', 'management', 'soft_skill', 'other', name='skillcategory'), nullable=True, comment='Sous-domaine optionnel : programming, ai_ml, database, devops…'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description libre de la compétence'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment="False = désactivée, non suggérée dans l'UI ni utilisée par le NLP"),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=True)
    op.create_index(op.f('ix_skills_normalized_name'), 'skills', ['normalized_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skills_normalized_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###