"""add jobs table

Revision ID: fb810d4cf680
Revises: 07d70c589999
Create Date: 2026-06-10 00:35:29.187362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb810d4cf680'
down_revision: Union[str, None] = '07d70c589999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Intitulé du poste'),
    sa.Column('company', sa.String(length=255), nullable=False, comment="Nom de l'entreprise"),
    sa.Column('description', sa.Text(), nullable=True, comment="Description complète de l'offre"),
    sa.Column('location', sa.String(length=255), nullable=True, comment='Ville / pays'),
    sa.Column('url', sa.String(length=500), nullable=True, comment="Lien vers l'offre originale"),
    sa.Column('contract_type', sa.Enum('CDI', 'CDD', 'Stage', 'Alternance', 'Freelance', 'Part-time', 'Volunteer', 'Other', name='contracttype'), nullable=False, comment='CDI, CDD, Stage, Alternance…'),
    sa.Column('experience_level', sa.Enum('junior', 'mid', 'senior', 'lead', 'internship', 'any', name='experiencelevel'), nullable=False, comment='junior, mid, senior, lead, internship, any'),
    sa.Column('work_mode', sa.Enum('on_site', 'remote', 'hybrid', 'any', name='workmode'), nullable=False, comment='on_site, remote, hybrid, any'),
    sa.Column('degree_level', sa.Enum('Bac+2', 'Bac+3', 'Bac+5', 'any', name='degreelevel'), nullable=True, comment='Bac+2, Bac+3, Bac+5…'),
    sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment="Liste des compétences normalisées : ['python', 'fastapi', 'sql']"),
    sa.Column('salary_min', sa.Float(), nullable=True, comment='Salaire minimum (DH)'),
    sa.Column('salary_max', sa.Float(), nullable=True, comment='Salaire maximum (DH)'),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('active', 'expired', 'suspended', 'draft', name='jobstatus'), nullable=False, comment='active, expired, suspended, draft'),
    sa.Column('source', sa.Enum('csv', 'json', 'scraper_rekrute', 'scraper_emploidiali', 'scraper_indeed', 'scraper_linkedin', 'manual', name='importsource'), nullable=False, comment="Origine de l'offre : csv, manual, scraper…"),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='Date de publication originale'),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment="Date d'expiration de l'offre"),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_company'), 'jobs', ['company'], unique=False)
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_location'), 'jobs', ['location'], unique=False)
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_location'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_company'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###